name: Publish Release to NPM

on: 
  push:
    tags:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.17.2"

  npm-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14.17.2"
        registry-url: https://registry.npmjs.org/
    - run: npm run start
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}